baseurl = "/"
languageCode = "de"
title = "Tavernetta Italiana"

[params]
  description = "Ihre italienische Tavernetta in München"

[[menu.main]]
    name = "Essen"
    url  = "/essen"
    weight = 1
[[menu.main]]
    name = "Getränke"
    url  = "/getraenke"
    weight = 2
[[menu.main]]
    name = "Über uns"
    url  = "/ueber_uns"
    weight = 3
[[menu.main]]
    name = "Gallerie"
    url  = "/gallerie"
    weight = 4
[[menu.main]]
     name = "Bei uns reservieren"
     url  = "/reservierung"
     weight = 5
