backend:
  name: github
  repo: tavernetta/homepage
  branch: master

media_folder: "src/img/gallerie" # Folder where user uploaded files should go
public_folder: "img/gallerie"

collections:
  - name: essen
    label: "Essen hinzufügen" # Used in the UI, ie.: "Neu hinzufügen"
    folder: "site/content/essen" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name des Gerichts", name: "title", widget: "string"}
      - {label: "Unterstützte Essen", name: "categories", widget: "list", default: ["mittags", "abends"]}
      - {label: "Zutaten/Beschreigung", name: "description", widget: "text"}
      - {label: "Art des Gerichts", name: "type", widget: "string", default: "warm"}
      - {label: "Preis", name: "price", widget: "string"}
  - name: getraenke
    label: "Getränk hinzufügen" # Used in the UI, ie.: "Neu hinzufügen"
    folder: "site/content/getraenke" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name des Getränks", name: "title", widget: "string"}
      - {label: "Hersteller", name: "categories", widget: "hidden", default: ["getraenk"]}
      - {label: "Zutaten/Beschreigung", name: "description", widget: "text"}
      - {label: "Art des Getränks", name: "type", widget: "string", default: "bier"}
      - {label: "Preis", name: "price", widget: "string"}
  - name: gallerie
    label: "Gallerie-Bild" # Used in the UI, ie.: "Neu hinzufügen"
    folder: "site/content/gallerie" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Gallerie Bild", name: "image", widget: "image"}
